version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run: python main.py

  test:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run: python test.py

  deploy:
    docker:
      - image: cimg/python:3.12
    steps:
      - run: echo 'practical done'

workflows:
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test